import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_subtitle': 'Learn Smarter, Grow Faster',
      'welcome_back': 'Welcome back! 👋',
      'sign_in_continue': 'Sign in to continue your learning journey.',
      'email_address': 'Email Address',
      'password': 'Password',
      'forgot_password': 'Forgot Password?',
      'sign_in': 'Sign In',
      'dont_have_account': "Don't have an account? ",
      'remember_me': 'Remember me',
      'or': 'or',
      'sign_up': 'Sign Up',
      'email_required': 'Please enter your email.',
      'email_invalid': 'Enter a valid email address.',
      'password_required': 'Please enter your password.',
      'password_too_short': 'Password must be at least 6 characters.',
      'login_failed': 'Failed to sign in. Please try again.',
      'create_account': 'Create Account',
      'join_learnnova': 'Join LearnNova and start learning smarter.',
      'full_name': 'Full Name',
      'your_full_name': 'Your full name',
      'name_too_short': 'Name must be at least 2 characters.',
      'password_strength': 'Password strength: ',
      'weak': 'Weak',
      'fair': 'Fair',
      'good': 'Good',
      'strong': 'Strong',
      'confirm_password_required': 'Please confirm your password.',
      'confirm_password': 'Confirm Password',
      'already_have_account': 'Already have an account? ',
      'name_required': 'Please enter your name.',
      'passwords_dont_match': 'Passwords do not match.',
      'register_failed': 'Failed to create account. Please try again.',
      'forgot_password_desc': "Enter your email below and we'll send you a link to reset your password.",
      'send_reset_link': 'Send Reset Link',
      'remember_password': 'Remember your password? ',
      'check_inbox': 'Check your inbox!',
      'reset_link_sent_to': "We've sent a password reset link to:",
      'check_spam': "Check your spam folder if you don't see it.",
      'resend_email': 'Resend Email',
      'back_to_sign_in': 'Back to Sign In',
      'reset_failed': 'Failed to send reset email. Please try again.',
      'home_title': 'LearnNova',
      'welcome_greeting': 'Welcome back,',
      'keep_up_work': 'Keep up the great work! 🔥',
      'all_modules': 'All Modules',
      'courses': 'courses',
      'lessons': 'lessons',
      'rating': 'Rating',
      'of': 'of',
      'modules_completed': 'Modules Completed',
      'done': 'done',
      'continue_learning': 'Continue Learning',
      'explore_modules': 'Explore Modules',
      'search_modules_topics': 'Search modules or topics...',
      'no_modules_found': 'No modules found',
      'topics_count': 'Topics',
      'start_learning': 'Start Learning',
      'resume': 'Resume',
      'completed': 'Completed',
      'in_progress': 'In Progress',
      'not_started': 'Not Started',
      'materials_completed': 'Materials Completed',
      'beginner': 'Beginner',
      'intermediate': 'Intermediate',
      'advanced': 'Advanced',
      'no_results_found': 'No results found matching your criteria.',
      'explorer_title': 'Explorer',
      'category_filter': 'Category',
      'difficulty_filter': 'Difficulty',
      'all_categories': 'All Categories',
      'all_difficulties': 'All Difficulties',
      'progress_title': 'Progress',
      'track_journey': 'Track your learning journey',
      'overall_progress': 'Overall Progress',
      'lessons_completed': 'Lessons Completed',
      'quizzes_passed': 'Quizzes Passed',
      'learning_streak': 'Learning Streak',
      'average_score': 'Average Score',
      'days': 'days',
      'day': 'day',
      'no_topics_completed': 'No topics completed yet',
      'complete_to_finish': 'Complete all 16 materials + the quiz to finish a topic.',
      'recently_completed': 'Recently Completed',
      'settings_title': 'Settings ⚙️',
      'manage_preferences': 'Manage your preferences',
      'edit_profile': 'Edit Profile',
      'update_personal_info': 'Update your personal info',
      'change_password': 'Change Password',
      'update_password': 'Update your password',
      'notifications': 'Notifications',
      'push_email_notif': 'Push, email notifications',
      'dark_mode': 'Dark Mode',
      'toggle_dark': 'Toggle dark appearance',
      'language': 'Language',
      'privacy_settings': 'Privacy Settings',
      'manage_data_permissions': 'Manage data & permissions',
      'help_support': 'Help & Support',
      'faqs_contact': 'FAQs, contact us',
      'send_feedback': 'Send Feedback',
      'share_thoughts': 'Share your thoughts',
      'about_learnnova': 'About LearnNova',
      'version_info': 'Version 1.0.0',
      'rate_us': 'Rate Us',
      'rate_us_desc': 'Love the app? Leave a review!',
      'logout': 'Log Out',
      'logout_question': 'Log Out?',
      'logout_confirm': 'Are you sure you want to log out of LearnNova?',
      'cancel': 'Cancel',
      'close': 'Close',
      'my_profile': 'My Profile',
      'personal_details_stats': 'Personal details & stats',
      'pro_learner': 'Pro Learner',
      'personal_details_header': 'PERSONAL DETAILS',
      'material_title': 'Material',
      'topic_title': 'Topic',
      'next': 'Next',
      'back': 'Back',
      'finish': 'Finish',
      'checkpoint_title': 'Checkpoint Question',
      'correct_feedback': 'Correct!',
      'incorrect_feedback': 'Incorrect',
      'explanation_label': 'Explanation',
      'continue_btn': 'Continue',
      'select_answer_alert': 'Please select an answer.',
      'quiz_title': 'Quiz',
      'final_quiz': 'Final Quiz',
      'question_label': 'Question',
      'submit_answer': 'Submit Answer',
      'quiz_results': 'Quiz Results',
      'congrats': 'Congratulations! 🎉',
      'you_passed': 'You passed the quiz!',
      'you_failed': 'You failed the quiz.',
      'quiz_failed_desc': 'You did not pass this quiz. Please review the materials and try again.',
      'your_score': 'Your Score',
      'passing_score': 'Passing Score',
      'correct_answers': 'Correct Answers',
      'review_answers': 'Review Answers',
      'retake_quiz': 'Retake Quiz',
      'coming_soon': 'Coming soon!',
      'photo_upload_coming': 'Photo upload coming soon!',
      'privacy_saved': 'Privacy settings saved!',
      'history_cleared': 'Activity history cleared!',
      'profile_updated': 'Profile updated successfully!',
      'enter_name': 'Please enter your name',
      'reset_email_sent': 'Password reset email sent!',
      'device_lang': 'System Language',
      'english': 'English',
      'indonesian': 'Bahasa Indonesia',
      'account': 'Account',
      'preferences': 'Preferences',
      'support': 'Support',
      'about': 'About',
      'about_desc': 'LearnNova v1.0.0\n\nLearn Smarter, Grow Faster.\n\nA modern educational platform designed to make learning engaging, effective, and fun.',
      // Category translations
      'category_programming': 'Programming',
      'category_design': 'Design',
      'category_animation': 'Animation',
      'category_business': 'Business',
      'category_languages': 'Languages',
      'category_academic': 'Academic',
      'category_creative': 'Creative',
      'category_sports_fitness': 'Sports & Fitness',
      // Explorer and Course list
      'all': 'All',
      'all_courses': 'All Courses',
      'found': 'found',
      'matching_topics': 'Matching Topics',
      'no_topics_match': 'No topics match your filters',
      'try_adjusting_filters': 'Try adjusting your search query, category, or difficulty level filters.',
      'trending_now': 'Trending Now',
      'most_popular': 'Most popular',
      'editors_picks': "Editor's picks",
      'featured_courses': 'Featured Courses',
      'trending': 'Trending',
      'discover_next_adventure': 'Discover your next learning adventure',
      'hot': 'Hot',
      'course': 'Course',
      // SubModule detail
      'learning_path': 'Learning Path',
      'certificate': 'Certificate',
      'your_progress': 'Your Progress',
      'topic_completed': 'Topic Completed!',
      'lesson': 'Lesson',
      'min': 'min',
      'quiz_passed_label': 'Quiz Passed:',
      'review_materials': 'Review Materials',
      'take_quiz': 'Take Quiz',
      'done_cap': 'Done',
      // Progress screen
      'day_streak': 'day streak',
      'overall_completion': 'Overall Completion',
      'remaining': 'Remaining',
      'modules': 'Modules',
      'topics_done': 'Topics Done',
      'day_streak_title': 'Day Streak',
      'lessons_done': 'Lessons Done',
      'avg_score_short': 'Avg Score',
      'weekly_activity': 'Weekly Activity',
      'this_week': 'This Week',
      'mon': 'Mon',
      'tue': 'Tue',
      'wed': 'Wed',
      'thu': 'Thu',
      'fri': 'Fri',
      'sat': 'Sat',
      'sun': 'Sun',
      'achievement_badges': 'Achievement Badges',
      'badge_streak_12': 'Streak 12',
      'badge_star_learner': 'Star Learner',
      'badge_champion': 'Champion',
      'badge_graduate': 'Graduate',
      'badge_diamond': 'Diamond',
      'badge_rocket': 'Rocket',
      'completed_topics': 'Completed Topics',
      'quiz_passed': 'Quiz Passed',
      // Profile screen
      'intermediate_level': 'Intermediate Level',
      'personal_information': 'Personal Information',
      'email': 'Email',
      'phone': 'Phone',
      'location': 'Location',
      'learning_level': 'Learning Level',
      'level_progress_desc': '{pct}% of topics completed — Keep it up! 🚀',
      // Edit Profile screen
      'basic_information': 'Basic Information',
      'phone_number': 'Phone Number',
      'city_country': 'City, Country',
      'about_you': 'About You',
      'bio': 'Bio',
      'bio_hint': 'Tell us about yourself...',
      'save': 'Save',
      'save_changes': 'Save Changes',
      // Privacy Settings screen
      'you_control_data': 'You control your data',
      'privacy_matters': 'Your Privacy Matters',
      'privacy_banner_desc': 'We never sell your personal data. These settings control how your information is used within LearnNova.',
      'data_analytics': 'Data & Analytics',
      'profile_visibility': 'Profile Visibility',
      'security': 'Security',
      'data_actions': 'Data Actions',
      'analytics_insights': 'Analytics & Insights',
      'analytics_desc': 'Help improve the app with anonymised usage data',
      'crash_reports': 'Crash Reports',
      'crash_desc': 'Automatically send crash reports to fix bugs',
      'personalised_ads': 'Personalised Ads',
      'ads_desc': 'Show relevant ads based on your learning',
      'usage_statistics': 'Usage Statistics',
      'usage_desc': 'Track study time and session data',
      'visibility_desc': 'Who can see your profile',
      'everyone': 'Everyone',
      'friends': 'Friends',
      'only_me': 'Only Me',
      'show_progress': 'Show Learning Progress',
      'show_progress_desc': 'Display course completion on profile',
      'show_badges': 'Show Badges & Achievements',
      'show_badges_desc': 'Display earned badges publicly',
      'appear_leaderboard': 'Appear in Leaderboard',
      'leaderboard_desc': 'Let others see your ranking',
      'two_factor': 'Two-Factor Authentication',
      'two_factor_desc': 'Extra security layer with SMS/email code',
      'login_alerts': 'Login Alerts',
      'login_alerts_desc': 'Get notified of new sign-ins',
      'active_sessions': 'Active Sessions',
      'sessions_desc': "Manage where you're logged in",
      'download_data': 'Download My Data',
      'download_data_desc': 'Get a copy of all your data',
      'clear_history': 'Clear Activity History',
      'clear_history_desc': 'Delete browsing & search history',
      'delete_account': 'Delete Account',
      'delete_account_desc': 'Permanently remove your account and data',
      'enable_2fa': 'Enable 2FA',
      'two_factor_dialog_desc': "Two-Factor Authentication adds an extra layer of security. You'll be prompted for a code when signing in on new devices.\n\nFull setup coming soon!",
      'clear_history_confirm': 'Clear Activity History?',
      'clear_history_warning': 'This will delete your browsing and search history. This action cannot be undone.',
      'clear': 'Clear',
      'delete_account_confirm': 'Delete Account?',
      'delete_account_warning': 'This is permanent. All your progress, certificates, and data will be deleted and CANNOT be recovered.',
      'delete': 'Delete',
      'data_export_coming': 'Data export coming soon',
      'account_deletion_coming': 'Account deletion coming soon',
      // Notification Settings screen
      'customize_alerts': 'Customize what you hear from us',
      'all_notifications': 'All Notifications',
      'master_switch': 'Master switch for all alerts',
      'learning_section': 'Learning',
      'achievements_social_section': 'Achievements & Social',
      'email_notif_section': 'Email Notifications',
      'daily_reminder_time': 'Daily Reminder Time',
      'daily_reminder': 'Daily Reminder',
      'daily_reminder_desc': 'Remind me to study each day',
      'course_updates': 'Course Updates',
      'course_updates_desc': 'New lessons added to enrolled courses',
      'streak_alerts': 'Streak Alerts',
      'streak_alerts_desc': "Don't break your learning streak!",
      'new_content': 'New Content',
      'new_content_desc': 'Fresh courses & modules',
      'achievements': 'Achievements',
      'achievements_desc': 'When you earn badges or level up',
      'leaderboard': 'Leaderboard',
      'notif_leaderboard_desc': 'Ranking changes & milestones',
      'community_activity': 'Community Activity',
      'community_desc': 'Replies, likes & mentions',
      'weekly_digest': 'Weekly Digest',
      'weekly_digest_desc': 'Your weekly learning summary',
      'promotions_offers': 'Promotions & Offers',
      'promotions_desc': 'Special deals and new features',
      'security_alerts': 'Security Alerts',
      'security_desc': 'Login attempts & account changes',
      'security_cannot_disable': 'Security alerts cannot be disabled',
      'notif_saved': 'Notification preferences saved!',
      // Help & Support screen
      'help_desc': "We're here to help you succeed",
      'message_sent': "Message sent! We'll reply within 24 hours.",
      'getting_started': 'Getting\nStarted',
      'video_tutorials': 'Video\nTutorials',
      'live_chat': 'Live\nChat',
      'email_us': 'Email\nUs',
      'faqs_title': 'FREQUENTLY ASKED QUESTIONS',
      'faq_q1': 'How do I enroll in a course?',
      'faq_a1': 'Go to the Explorer tab, find a course you like, and tap "Enroll Now." Enrolled courses appear on your Home screen for easy access.',
      'faq_q2': 'How does the streak system work?',
      'faq_a2': 'Complete at least one lesson per day to maintain your streak 🔥. Missing a day resets it to 0. You can protect your streak with a "Streak Shield" from the store.',
      'faq_q3': 'Can I download content for offline access?',
      'faq_a3': 'Offline downloads are available for Pro subscribers. Tap the download icon on any lesson to save it for offline viewing.',
      'faq_q4': 'How do I get a certificate?',
      'faq_a4': 'Complete all lessons and pass the final quiz (score ≥ 70%) in a course. Your certificate is instantly generated and available in your Profile.',
      'faq_q5': 'How do I change my password?',
      'faq_a5': 'Go to Settings → Account → Change Password. You will receive a password reset link via email.',
      'faq_q6': 'How do I cancel my subscription?',
      'faq_a6': 'Navigate to Settings → Account → Manage Subscription. You can cancel anytime; access continues until the end of the billing period.',
      'faq_q7': 'My video is not loading, what should I do?',
      'faq_a7': 'Check your internet connection first. If the issue persists, try closing and reopening the app. You can also report the issue using the feedback form below.',
      'send_message_title': 'SEND US A MESSAGE',
      'topic_general': 'General',
      'topic_technical': 'Technical Issue',
      'topic_billing': 'Billing',
      'topic_content': 'Course Content',
      'topic_account': 'Account',
      'topic_other': 'Other',
      'topic': 'Topic',
      'enter_subject': 'Please enter a subject',
      'subject': 'Subject',
      'enter_message_min': 'Please write at least 10 characters',
      'message': 'Message',
      'send_message': 'Send Message',
      // Material Study screen
      'failed_load_materials': 'Failed to load materials. Please try again.',
      'viewed': 'viewed',
      'loading_materials': 'Loading materials...',
      'retry': 'Retry',
      'viewed_cap': 'Viewed',
      'example_code': 'Example Code',
      'copied_clipboard': 'Code copied to clipboard!',
      'copy': 'Copy',
      'previous': 'Previous',
      'materials_completed_msg': '🎉 All 16 materials completed! Quiz is now unlocked.',
      'finish_unlock_quiz': 'Finish & Unlock Quiz',
      'view_all_slides': 'View All Slides First',
      'after_slide': 'After Slide {num}',
      'select_answer_continue': 'Select an answer to continue',
      // Quiz play screen
      'failed_load_quiz': 'Failed to load quiz. Please try again.',
      'loading_quiz': 'Loading quiz...',
      'correct': 'correct',
      'correct_answer_is': 'Correct answer: {ans}',
      'see_results': 'See Results',
      'next_question': 'Next Question',
      // Quiz Result screen
      'passed_badge': 'PASSED',
      'failed_badge': 'FAILED — Try Again',
      'correct_label': 'Correct',
      'wrong_label': 'Wrong',
      'total_label': 'Total',
      'quiz_passed_congrats': 'Congratulations! The topic "{topic}" is now marked as completed.',
      'min_passing_score_info': 'Minimum passing score is 60%. Review the materials and try again.',
      'back_to_topic': 'Back to Topic',
      // Quiz Review screen
      'quiz_review_title': 'Quiz Review',
      'score_label': 'Score',
    },
    'id': {
      'app_subtitle': 'Belajar Lebih Cerdas, Tumbuh Lebih Cepat',
      'welcome_back': 'Selamat datang kembali! 👋',
      'sign_in_continue': 'Masuk untuk melanjutkan perjalanan belajar Anda.',
      'email_address': 'Alamat Email',
      'password': 'Kata Sandi',
      'forgot_password': 'Lupa Kata Sandi?',
      'sign_in': 'Masuk',
      'dont_have_account': 'Belum punya akun? ',
      'remember_me': 'Ingat saya',
      'or': 'atau',
      'sign_up': 'Daftar',
      'email_required': 'Silakan masukkan email Anda.',
      'email_invalid': 'Masukkan alamat email yang valid.',
      'password_required': 'Silakan masukkan kata sandi Anda.',
      'password_too_short': 'Kata sandi harus minimal 6 karakter.',
      'login_failed': 'Gagal masuk. Silakan coba lagi.',
      'create_account': 'Buat Akun',
      'join_learnnova': 'Bergabunglah dengan LearnNova dan mulailah belajar lebih cerdas.',
      'full_name': 'Nama Lengkap',
      'your_full_name': 'Nama lengkap Anda',
      'name_too_short': 'Nama harus minimal 2 karakter.',
      'password_strength': 'Kekuatan kata sandi: ',
      'weak': 'Lemah',
      'fair': 'Cukup',
      'good': 'Baik',
      'strong': 'Kuat',
      'confirm_password_required': 'Silakan konfirmasi kata sandi Anda.',
      'confirm_password': 'Konfirmasi Kata Sandi',
      'already_have_account': 'Sudah punya akun? ',
      'name_required': 'Silakan masukkan nama Anda.',
      'passwords_dont_match': 'Kata sandi tidak cocok.',
      'register_failed': 'Gagal membuat akun. Silakan coba lagi.',
      'forgot_password_desc': 'Masukkan email Anda di bawah ini dan kami akan mengirimkan tautan untuk mengatur ulang kata sandi Anda.',
      'send_reset_link': 'Kirim Tautan Atur Ulang',
      'remember_password': 'Ingat kata sandi Anda? ',
      'check_inbox': 'Periksa kotak masuk Anda!',
      'reset_link_sent_to': 'Kami telah mengirimkan tautan atur ulang kata sandi ke:',
      'check_spam': 'Periksa folder spam Anda jika tidak melihatnya.',
      'resend_email': 'Kirim Ulang Email',
      'back_to_sign_in': 'Kembali ke Halaman Masuk',
      'reset_failed': 'Gagal mengirim email atur ulang. Silakan coba lagi.',
      'home_title': 'LearnNova',
      'welcome_greeting': 'Selamat datang kembali,',
      'keep_up_work': 'Pertahankan kerja bagus! 🔥',
      'all_modules': 'Semua Modul',
      'courses': 'kursus',
      'lessons': 'pelajaran',
      'rating': 'Penilaian',
      'of': 'dari',
      'modules_completed': 'Modul Selesai',
      'done': 'selesai',
      'continue_learning': 'Lanjutkan Belajar',
      'explore_modules': 'Jelajahi Modul',
      'search_modules_topics': 'Cari modul atau topik...',
      'no_modules_found': 'Modul tidak ditemukan',
      'topics_count': 'Topik',
      'start_learning': 'Mulai Belajar',
      'resume': 'Lanjutkan',
      'completed': 'Selesai',
      'in_progress': 'Sedang Berjalan',
      'not_started': 'Belum Dimulai',
      'materials_completed': 'Materi Selesai',
      'beginner': 'Pemula',
      'intermediate': 'Menengah',
      'advanced': 'Mahir',
      'no_results_found': 'Hasil tidak ditemukan yang cocok dengan kriteria Anda.',
      'explorer_title': 'Penjelajah',
      'category_filter': 'Kategori',
      'difficulty_filter': 'Kesulitan',
      'all_categories': 'Semua Kategori',
      'all_difficulties': 'Semua Kesulitan',
      'progress_title': 'Kemajuan',
      'track_journey': 'Pantau perjalanan belajar Anda',
      'overall_progress': 'Kemajuan Keseluruhan',
      'lessons_completed': 'Pelajaran Selesai',
      'quizzes_passed': 'Kuis Lulus',
      'learning_streak': 'Streak Belajar',
      'average_score': 'Nilai Rata-rata',
      'days': 'hari',
      'day': 'hari',
      'no_topics_completed': 'Belum ada topik yang selesai',
      'complete_to_finish': 'Selesaikan semua 16 materi + kuis untuk menyelesaikan topik.',
      'recently_completed': 'Baru Saja Selesai',
      'settings_title': 'Pengaturan ⚙️',
      'manage_preferences': 'Kelola preferensi Anda',
      'edit_profile': 'Edit Profil',
      'update_personal_info': 'Perbarui info pribadi Anda',
      'change_password': 'Ubah Kata Sandi',
      'update_password': 'Perbarui kata sandi Anda',
      'notifications': 'Notifikasi',
      'push_email_notif': 'Notifikasi push & email',
      'dark_mode': 'Mode Gelap',
      'toggle_dark': 'Ubah tampilan gelap',
      'language': 'Bahasa',
      'privacy_settings': 'Pengaturan Privasi',
      'manage_data_permissions': 'Kelola data & izin',
      'help_support': 'Bantuan & Dukungan',
      'faqs_contact': 'FAQ, hubungi kami',
      'send_feedback': 'Kirim Umpan Balik',
      'share_thoughts': 'Bagikan pemikiran Anda',
      'about_learnnova': 'Tentang LearnNova',
      'version_info': 'Versi 1.0.0',
      'rate_us': 'Beri Nilai Kami',
      'rate_us_desc': 'Suka aplikasinya? Berikan ulasan!',
      'logout': 'Keluar',
      'logout_question': 'Keluar?',
      'logout_confirm': 'Apakah Anda yakin ingin keluar dari LearnNova?',
      'cancel': 'Batal',
      'close': 'Tutup',
      'my_profile': 'Profil Saya',
      'personal_details_stats': 'Detail & statistik pribadi',
      'pro_learner': 'Pembelajar Pro',
      'personal_details_header': 'DETAIL PRIBADI',
      'material_title': 'Materi',
      'topic_title': 'Topik',
      'next': 'Berikutnya',
      'back': 'Kembali',
      'finish': 'Selesai',
      'checkpoint_title': 'Pertanyaan Checkpoint',
      'correct_feedback': 'Benar!',
      'incorrect_feedback': 'Salah',
      'explanation_label': 'Penjelasan',
      'continue_btn': 'Lanjutkan',
      'select_answer_alert': 'Silakan pilih jawaban.',
      'quiz_title': 'Kuis',
      'final_quiz': 'Kuis Akhir',
      'question_label': 'Pertanyaan',
      'submit_answer': 'Kirim Jawaban',
      'quiz_results': 'Hasil Kuis',
      'congrats': 'Selamat! 🎉',
      'you_passed': 'Anda lulus kuis!',
      'you_failed': 'Anda gagal kuis.',
      'quiz_failed_desc': 'Anda tidak lulus kuis ini. Silakan tinjau materi dan coba lagi.',
      'your_score': 'Skor Anda',
      'passing_score': 'Skor Kelulusan',
      'correct_answers': 'Jawaban Benar',
      'review_answers': 'Tinjau Jawaban',
      'retake_quiz': 'Ulangi Kuis',
      'coming_soon': 'Segera hadir!',
      'photo_upload_coming': 'Unggah foto segera hadir!',
      'privacy_saved': 'Pengaturan privasi disimpan!',
      'history_cleared': 'Riwayat aktivitas dibersihkan!',
      'profile_updated': 'Profil berhasil diperbarui!',
      'enter_name': 'Silakan masukkan nama Anda',
      'reset_email_sent': 'Email atur ulang kata sandi terkirim!',
      'device_lang': 'Bahasa Sistem',
      'english': 'English',
      'indonesian': 'Bahasa Indonesia',
      'account': 'Akun',
      'preferences': 'Preferensi',
      'support': 'Dukungan',
      'about': 'Tentang',
      'about_desc': 'LearnNova v1.0.0\n\nBelajar Lebih Cerdas, Tumbuh Lebih Cepat.\n\nPlatform pendidikan modern yang dirancang untuk membuat pembelajaran menjadi menarik, efektif, dan menyenangkan.',
      // Category translations
      'category_programming': 'Pemrograman',
      'category_design': 'Desain',
      'category_animation': 'Animasi',
      'category_business': 'Bisnis',
      'category_languages': 'Bahasa',
      'category_academic': 'Akademik',
      'category_creative': 'Kreatif',
      'category_sports_fitness': 'Olahraga & Kebugaran',
      // Explorer and Course list
      'all': 'Semua',
      'all_courses': 'Semua Kursus',
      'found': 'ditemukan',
      'matching_topics': 'Topik yang Cocok',
      'no_topics_match': 'Tidak ada topik yang cocok dengan filter Anda',
      'try_adjusting_filters': 'Coba sesuaikan kueri pencarian, kategori, atau filter tingkat kesulitan Anda.',
      'trending_now': 'Sedang Tren Sekarang',
      'most_popular': 'Paling populer',
      'editors_picks': 'Pilihan editor',
      'featured_courses': 'Kursus Pilihan',
      'trending': 'Sedang Tren',
      'discover_next_adventure': 'Temukan petualangan belajar Anda berikutnya',
      'hot': 'Populer',
      'course': 'Kursus',
      // SubModule detail
      'learning_path': 'Alur Belajar',
      'certificate': 'Sertifikat',
      'your_progress': 'Kemajuan Anda',
      'topic_completed': 'Topik Selesai!',
      'lesson': 'Pelajaran',
      'min': 'menit',
      'quiz_passed_label': 'Kuis Lulus:',
      'review_materials': 'Tinjau Materi',
      'take_quiz': 'Kerjakan Kuis',
      'done_cap': 'Selesai',
      // Progress screen
      'day_streak': 'hari beruntun',
      'overall_completion': 'Penyelesaian Keseluruhan',
      'remaining': 'Tersisa',
      'modules': 'Modul',
      'topics_done': 'Topik Selesai',
      'day_streak_title': 'Streak Hari',
      'lessons_done': 'Pelajaran Selesai',
      'avg_score_short': 'Nilai Rata-rata',
      'weekly_activity': 'Aktivitas Mingguan',
      'this_week': 'Minggu Ini',
      'mon': 'Sen',
      'tue': 'Sel',
      'wed': 'Rab',
      'thu': 'Kam',
      'fri': 'Jum',
      'sat': 'Sab',
      'sun': 'Min',
      'achievement_badges': 'Lencana Prestasi',
      'badge_streak_12': 'Streak 12',
      'badge_star_learner': 'Pembelajar Bintang',
      'badge_champion': 'Juara',
      'badge_graduate': 'Lulusan',
      'badge_diamond': 'Berlian',
      'badge_rocket': 'Roket',
      'completed_topics': 'Topik yang Selesai',
      'quiz_passed': 'Kuis Lulus',
      // Profile screen
      'intermediate_level': 'Tingkat Menengah',
      'personal_information': 'Informasi Pribadi',
      'email': 'Email',
      'phone': 'Telepon',
      'location': 'Lokasi',
      'learning_level': 'Level Belajar',
      'level_progress_desc': '{pct}% topik selesai — Pertahankan! 🚀',
      // Edit Profile screen
      'basic_information': 'Informasi Dasar',
      'phone_number': 'Nomor Telepon',
      'city_country': 'Kota, Negara',
      'about_you': 'Tentang Anda',
      'bio': 'Bio',
      'bio_hint': 'Ceritakan tentang diri Anda...',
      'save': 'Simpan',
      'save_changes': 'Simpan Perubahan',
      // Privacy Settings screen
      'you_control_data': 'Anda mengontrol data Anda',
      'privacy_matters': 'Privasi Anda Sangat Penting',
      'privacy_banner_desc': 'Kami tidak pernah menjual data pribadi Anda. Pengaturan ini mengontrol bagaimana informasi Anda digunakan dalam LearnNova.',
      'data_analytics': 'Data & Analisis',
      'profile_visibility': 'Visibilitas Profil',
      'security': 'Keamanan',
      'data_actions': 'Tindakan Data',
      'analytics_insights': 'Analisis & Wawasan',
      'analytics_desc': 'Membantu meningkatkan aplikasi dengan data penggunaan anonim',
      'crash_reports': 'Laporan Crash',
      'crash_desc': 'Kirim laporan crash secara otomatis untuk memperbaiki bug',
      'personalised_ads': 'Iklan yang Personal',
      'ads_desc': 'Tampilkan iklan yang relevan berdasarkan pembelajaran Anda',
      'usage_statistics': 'Statistik Penggunaan',
      'usage_desc': 'Lacak waktu belajar dan data sesi',
      'visibility_desc': 'Siapa yang dapat melihat profil Anda',
      'everyone': 'Semua Orang',
      'friends': 'Teman',
      'only_me': 'Hanya Saya',
      'show_progress': 'Tampilkan Kemajuan Belajar',
      'show_progress_desc': 'Tampilkan penyelesaian kursus pada profil',
      'show_badges': 'Tampilkan Lencana & Prestasi',
      'show_badges_desc': 'Tampilkan lencana yang diperoleh secara publik',
      'appear_leaderboard': 'Muncul di Papan Peringkat',
      'leaderboard_desc': 'Biarkan orang lain melihat peringkat Anda',
      'two_factor': 'Autentikasi Dua Faktor',
      'two_factor_desc': 'Lapisan keamanan tambahan dengan kode SMS/email',
      'login_alerts': 'Pemberitahuan Masuk',
      'login_alerts_desc': 'Dapatkan notifikasi jika ada masuk baru',
      'active_sessions': 'Sesi Aktif',
      'sessions_desc': 'Kelola di mana Anda masuk',
      'download_data': 'Unduh Data Saya',
      'download_data_desc': 'Dapatkan salinan dari semua data Anda',
      'clear_history': 'Bersihkan Riwayat Aktivitas',
      'clear_history_desc': 'Hapus riwayat penelusuran & pencarian',
      'delete_account': 'Hapus Akun',
      'delete_account_desc': 'Hapus akun dan data Anda secara permanen',
      'enable_2fa': 'Aktifkan 2FA',
      'two_factor_dialog_desc': 'Autentikasi Dua Faktor menambahkan lapisan keamanan ekstra. Anda akan dimintai kode saat masuk di perangkat baru.\n\nPenyiapan lengkap segera hadir!',
      'clear_history_confirm': 'Bersihkan Riwayat Aktivitas?',
      'clear_history_warning': 'Ini akan menghapus riwayat penelusuran dan pencarian Anda. Tindakan ini tidak dapat dibatalkan.',
      'clear': 'Bersihkan',
      'delete_account_confirm': 'Hapus Akun?',
      'delete_account_warning': 'Ini bersifat permanen. Semua kemajuan, sertifikat, dan data Anda akan dihapus dan TIDAK BISA dipulihkan.',
      'delete': 'Hapus',
      'data_export_coming': 'Ekspor data segera hadir',
      'account_deletion_coming': 'Penghapusan akun segera hadir',
      // Notification Settings screen
      'customize_alerts': 'Sesuaikan notifikasi yang Anda terima',
      'all_notifications': 'Semua Notifikasi',
      'master_switch': 'Sakelar utama untuk semua notifikasi',
      'learning_section': 'Pembelajaran',
      'achievements_social_section': 'Prestasi & Sosial',
      'email_notif_section': 'Notifikasi Email',
      'daily_reminder_time': 'Waktu Pengingat Harian',
      'daily_reminder': 'Pengingat Harian',
      'daily_reminder_desc': 'Ingatkan saya untuk belajar setiap hari',
      'course_updates': 'Pembaruan Kursus',
      'course_updates_desc': 'Pelajaran baru ditambahkan ke kursus yang diikuti',
      'streak_alerts': 'Peringatan Streak',
      'streak_alerts_desc': 'Jangan biarkan streak belajar Anda terputus!',
      'new_content': 'Konten Baru',
      'new_content_desc': 'Kursus & modul baru',
      'achievements': 'Prestasi',
      'achievements_desc': 'Saat Anda mendapatkan lencana atau naik level',
      'leaderboard': 'Papan Peringkat',
      'notif_leaderboard_desc': 'Perubahan peringkat & pencapaian',
      'community_activity': 'Aktivitas Komunitas',
      'community_desc': 'Balasan, suka & sebutan',
      'weekly_digest': 'Rangkuman Mingguan',
      'weekly_digest_desc': 'Ringkasan pembelajaran mingguan Anda',
      'promotions_offers': 'Promosi & Penawaran',
      'promotions_desc': 'Penawaran khusus dan fitur baru',
      'security_alerts': 'Peringatan Keamanan',
      'security_desc': 'Upaya masuk & perubahan akun',
      'security_cannot_disable': 'Peringatan keamanan tidak dapat dinonaktifkan',
      'notif_saved': 'Preferensi notifikasi disimpan!',
      // Help & Support screen
      'help_desc': 'Kami di sini untuk membantu Anda sukses',
      'message_sent': 'Pesan terkirim! Kami akan membalas dalam waktu 24 jam.',
      'getting_started': 'Mulai\nBelajar',
      'video_tutorials': 'Tutorial\nVideo',
      'live_chat': 'Obrolan\nLangsung',
      'email_us': 'Kirim\nEmail',
      'faqs_title': 'PERTANYAAN YANG SERING DIAJUKAN',
      'faq_q1': 'Bagaimana cara mendaftar kursus?',
      'faq_a1': 'Buka tab Penjelajah, cari kursus yang Anda suka, dan ketuk "Daftar Sekarang". Kursus yang didaftarkan akan muncul di layar Beranda Anda untuk akses mudah.',
      'faq_q2': 'Bagaimana cara kerja sistem streak?',
      'faq_a2': 'Selesaikan setidaknya satu pelajaran per hari untuk mempertahankan streak Anda 🔥. Melewatkan satu hari akan mengatur ulangnya ke 0. Anda dapat melindungi streak Anda dengan "Streak Shield" dari toko.',
      'faq_q3': 'Apakah saya bisa mengunduh konten untuk akses offline?',
      'faq_a3': 'Unduhan offline tersedia untuk pelanggan Pro. Ketuk ikon unduh pada pelajaran apa saja untuk menyimpannya untuk penayangan offline.',
      'faq_q4': 'Bagaimana cara mendapatkan sertifikat?',
      'faq_a4': 'Selesaikan semua pelajaran dan lulus kuis akhir (skor ≥ 70%) di sebuah kursus. Sertifikat Anda langsung dibuat dan tersedia di Profil Anda.',
      'faq_q5': 'Bagaimana cara mengubah kata sandi saya?',
      'faq_a5': 'Buka Pengaturan → Akun → Ubah Kata Sandi. Anda akan menerima tautan atur ulang kata sandi melalui email.',
      'faq_q6': 'Bagaimana cara membatalkan langganan saya?',
      'faq_a6': 'Buka Pengaturan → Akun → Kelola Langganan. Anda dapat membatalkan kapan saja; akses berlanjut hingga akhir periode penagihan.',
      'faq_q7': 'Video saya tidak bisa dimuat, apa yang harus saya lakukan?',
      'faq_a7': 'Periksa koneksi internet Anda terlebih dahulu. Jika masalah berlanjut, coba tutup dan buka kembali aplikasi. Anda juga dapat melaporkan masalah tersebut menggunakan formulir umpan balik di bawah ini.',
      'send_message_title': 'KIRIM PESAN KEPADA KAMI',
      'topic_general': 'Umum',
      'topic_technical': 'Masalah Teknis',
      'topic_billing': 'Penagihan',
      'topic_content': 'Konten Kursus',
      'topic_account': 'Akun',
      'topic_other': 'Lainnya',
      'topic': 'Topik',
      'enter_subject': 'Silakan masukkan subjek',
      'subject': 'Subjek',
      'enter_message_min': 'Silakan tulis minimal 10 karakter',
      'message': 'Pesan',
      'send_message': 'Kirim Pesan',
      // Material Study screen
      'failed_load_materials': 'Gagal memuat materi. Silakan coba lagi.',
      'viewed': 'dilihat',
      'loading_materials': 'Memuat materi...',
      'retry': 'Coba Lagi',
      'viewed_cap': 'Dilihat',
      'example_code': 'Contoh Kode',
      'copied_clipboard': 'Kode disalin ke papan klip!',
      'copy': 'Salin',
      'previous': 'Sebelumnya',
      'materials_completed_msg': '🎉 Semua 16 materi selesai! Kuis sekarang terbuka.',
      'finish_unlock_quiz': 'Selesai & Buka Kuis',
      'view_all_slides': 'Lihat Semua Slide Terlebih Dahulu',
      'after_slide': 'Setelah Slide {num}',
      'select_answer_continue': 'Pilih jawaban untuk melanjutkan',
      // Quiz play screen
      'failed_load_quiz': 'Gagal memuat kuis. Silakan coba lagi.',
      'loading_quiz': 'Memuat kuis...',
      'correct': 'benar',
      'correct_answer_is': 'Jawaban benar: {ans}',
      'see_results': 'Lihat Hasil',
      'next_question': 'Pertanyaan Berikutnya',
      // Quiz Result screen
      'passed_badge': 'LULUS',
      'failed_badge': 'GAGAL — Coba Lagi',
      'correct_label': 'Benar',
      'wrong_label': 'Salah',
      'total_label': 'Total',
      'quiz_passed_congrats': 'Selamat! Topik "{topic}" sekarang ditandai sebagai selesai.',
      'min_passing_score_info': 'Skor kelulusan minimum adalah 60%. Tinjau materi dan coba lagi.',
      'back_to_topic': 'Kembali ke Topik',
      // Quiz Review screen
      'quiz_review_title': 'Tinjau Kuis',
      'score_label': 'Skor',
    }
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'id'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(AppLocalizations(locale));
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

extension LocalizationExtension on BuildContext {
  String tr(String key) {
    return AppLocalizations.of(this)?.translate(key) ?? key;
  }
}
