// File generated by FlutterFire CLI.
// Run `flutterfire configure` to regenerate this file with your actual Firebase project values.
// See: https://firebase.flutter.dev/docs/cli

// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
/// ⚠️  IMPORTANT: This is a PLACEHOLDER file.
/// Replace the values below with your actual Firebase project configuration by
/// running `flutterfire configure` from the project root.
///
/// Installation steps:
///   1. Install FlutterFire CLI: `dart pub global activate flutterfire_cli`
///   2. Run: `flutterfire configure`
///   3. Select your Firebase project (or create one)
///   4. This file will be overwritten with real credentials
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ────────────────────────────────────────────────────────────────────────────
  // ⚠️  Replace ALL placeholder values below with real ones from your Firebase
  //    project. Run `flutterfire configure` to do this automatically.
  // ────────────────────────────────────────────────────────────────────────────

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyBiMV2fsOw8EWNNnzCLdYWk3oIIdKxvI',
    appId: '1:88290025375:web:f60db9bd6f22f11109a7aa',
    messagingSenderId: '88290025375',
    projectId: 'learnova-281e0',
    authDomain: 'learnova-281e0.firebaseapp.com',
    storageBucket: 'learnova-281e0.firebasestorage.app',
    measurementId: 'G-M8EFHHGRLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGlNEMgXCpy6pn_t2zcNMRug7vivjKyKM',
    appId: '1:88290025375:android:c7b49370e7234b7e09a7aa',
    messagingSenderId: '88290025375',
    projectId: 'learnova-281e0',
    storageBucket: 'learnova-281e0.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwi3eF__JTylUkROPgkaUJBYEbf2R7Uoo',
    appId: '1:88290025375:ios:2ce89962f55c619a09a7aa',
    messagingSenderId: '88290025375',
    projectId: 'learnova-281e0',
    storageBucket: 'learnova-281e0.firebasestorage.app',
    iosClientId: '88290025375-gkso1sl38vouh0ssdh8i4m1hlrfjtt5v.apps.googleusercontent.com',
    iosBundleId: 'com.learnnova.learnnova',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwi3eF__JTylUkROPgkaUJBYEbf2R7Uoo',
    appId: '1:88290025375:ios:2ce89962f55c619a09a7aa',
    messagingSenderId: '88290025375',
    projectId: 'learnova-281e0',
    storageBucket: 'learnova-281e0.firebasestorage.app',
    iosClientId: '88290025375-gkso1sl38vouh0ssdh8i4m1hlrfjtt5v.apps.googleusercontent.com',
    iosBundleId: 'com.learnnova.learnnova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyBiMV2fsOw8EWNNnzCLdYWk3oIIdKxvI',
    appId: '1:88290025375:web:05e5a0ef1dd7f37b09a7aa',
    messagingSenderId: '88290025375',
    projectId: 'learnova-281e0',
    authDomain: 'learnova-281e0.firebaseapp.com',
    storageBucket: 'learnova-281e0.firebasestorage.app',
    measurementId: 'G-VSSRSVFLLL',
  );
}
